# Site wide configuration

title: Christ on the Mountain Top
description: Friends. Purpose. Life.
logo: logo.png # 120x120 px default image used for Twitter summary card
teaser: teaser.png # 400x250 px default teaser image used in image archive grid
locale: en
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Jesse P Bohanan
  email: thoughthaven@gmail.com
  twitter: justathoughtor2
  google:
    ad-client:
    ad-slot:
  bio: Something untraditional.
  avatar: avatars/justathoughtor2-avatar.png # 160x160 px image for author byline
  disqus-shortname:


# Site authors
data:
  authors:
    bohanan.jp:
      name: JP Bohanan
      email: bohanan.jp@gmail.com
      twitter:
      bio:
      avatar: bio-photo.jpg
    justathoughtor2:
      name: Jesse P Bohanan
      email: thoughthaven@gmail.com
      twitter: justathoughtor2
      bio: Something untraditional.
      avatar: avatars/justathoughtor2-avatar.png


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
